### ISSUE TITLE
share data

### ISSUE THREAD

**Issue by Carklitos** [mauricelambert/SpyWare#2]
is it possible to send the data of the person who opens the spyware to another pc?

**Comment by mauricelambert** [comment]
Yes it's possible.

Step 1: Compress data in a archive file (a ZIP file or compressed tar archive).
Step 2: Check the victim's computer have access to your computer (for example in a local network) or to your public server (if victim's network doesn't have any firewall it's probably the best solution).
Step 3: Send it with a socket, it's easy to use HTTP to extract data but you can you any protocol (DNS, NTP, SNMP, a simple TCP/UDP socket...).

I don't share this solution because data extraction is really simple without any protection like a firewall, but you need to implement your custom solution when there is a firewall on the victim's network to bypass it.

It's a complete package to make a data extractor to bypass firewall, you can use steganography or/and trusted API like linkedin, telegram...

I will probably write an extractor in the future, but not now.
